sudo: false
dist: trusty

language: node_js

cache:
  yarn: true

node_js:
- '4'
- '6'
- node

jdk:
- oraclejdk8

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.1.0
- export PATH=$HOME/.yarn/bin:$PATH

script:
- npm run test
